FROM postgres:9.4

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales nano sed vim curl supervisor sudo postgresql-client-9.4

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV TERM xterm
ENV POSTGRES_USER postgres
ENV PGDATA /var/lib/postgresql/data/pgdata
