onboarding:
  build: .

  links:
    - db-server:db-server
  volumes:
     - /tmp/data-onisep:/data

  ports:
       - "11080:8080"
       - "11022:22"
       - "11432:5432"
       - "8000:8000"



db-server:
  container_name: db-server
  build: .
  dockerfile: Dockerfile_pg
  environment:
    POSTGRES_USER: postgres
    PGDATA: /var/lib/postgresql/data/pgdata

  volumes:
    - /var/lib/docker/volumes/data/_data:/var/lib/postgresql/data/pgdata